# -*- coding: utf-8 -*-
"""
Created on 2025-05-21 22:39:56
---------
@summary:
---------
@author: lan
"""

from feapder import Item


class WpShopInfoItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i wp_shop_info
    """

    __table_name__ = "wp_shop_info"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.price = None
