# -*- coding: utf-8 -*-
"""
Created on 2025-05-21 19:13:30
---------
@summary:
---------
@author: lan
"""

from feapder import Item


class DoubanItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i douban
    """

    __table_name__ = "douban"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None
        self.score = None
        self.detail_url = None
        self.detail_text = None
